### ISSUE TITLE
Collision area of torch is unclear

### ISSUE THREAD

**Issue by daveallenbpm** [to-the-end/to-the-end#75]
The background for the torch should indicate the collision / activation area for the torch. Maybe something like a darker brown (indicating a wooden platform for the torch) or similar could work.

**Comment by erbridge** [comment]
That or just make make it tighter to the torch itself (it doesn't need to be square, or match the grid size).

**Comment by daveallenbpm** [comment]
That should be fine. I'll take a look at your changes this evening - more than likely this'll have resolved the issue.

**Comment by erbridge** [comment]
It's still a bit rubbish when the torch is off. Especially at the top. When it's on it's fine, though...

**Comment by daveallenbpm** [comment]
It's an improvement, but as you say it looks a little odd when the torch is off. I think having something in the background representing the collision area would help. Alternatively, we could remove the collision from the flame so you collide with the top of the torch instead, and have it so that the flame is layered over the character when he's walking past the top of the torch.

**Comment by erbridge** [comment]
I think the second solution will work for now.
